version: '3.8'

services:
  app:
    container_name: kjtp-app
    image: javierromeroup/kjtp-app:1.0.0
    ports:
      - "9000:9000"
    environment:
      - KEYCLOAK_HOST=kjtp-keycloak
    depends_on:
      - app-db
      - keycloak-db
      - keycloak
    networks:
      - kjtp-network
    restart: always

  app-db:
    container_name: kjtp-app-db
    image: postgres:16-alpine3.18
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=kjtp-app_db
      - POSTGRES_USER=kjtp-admin
      - POSTGRES_PASSWORD=873264ygy!@E
    volumes:
      - project-db-volume:/var/lib/postgresql/data
    networks:
      - kjtp-network
    restart: always

  keycloak:
    container_name: kjtp-keycloak
    image: bitnami/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_VENDOR=postgresql
      - KEYCLOAK_DATABASE_HOST=kjtp-keycloak-db
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=keycloak_db
      - KEYCLOAK_DATABASE_USER=keycloak_admin
      - KEYCLOAK_DATABASE_PASSWORD=872r#@6afb
    depends_on:
      - keycloak-db
    networks:
      - kjtp-network
    restart: always

  keycloak-db:
    container_name: kjtp-keycloak-db
    image: postgres:16-alpine3.18
    environment:
      - POSTGRES_DB=keycloak_db
      - POSTGRES_USER=keycloak_admin
      - POSTGRES_PASSWORD=872r#@6afb
    volumes:
      - keycloak-db-volume:/var/lib/postgresql/data
    networks:
      - kjtp-network
    restart: always

volumes:
  project-db-volume:
    external: false
  keycloak-db-volume:
    external: false

networks:
  kjtp-network: